apiVersion: v1
kind: ServiceAccount
metadata:
  name: clustertree
  namespace: kosmos-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustertree
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ["*"]
  - nonResourceURLs: ['*']
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clustertree
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clustertree
subjects:
  - kind: ServiceAccount
    name: clustertree
    namespace: kosmos-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clustertree-cluster-manager
  namespace: kosmos-system
  labels:
    app: clustertree-cluster-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clustertree-cluster-manager
  template:
    metadata:
      labels:
        app: clustertree-cluster-manager
    spec:
      serviceAccountName: clustertree
      containers:
        - name: clustertree-cluster-manager
          image: ghcr.io/kosmos-io/clustertree-cluster-manager:__VERSION__
          imagePullPolicy: Always
          command:
            - clustertree-cluster-manager
            - --multi-cluster-service=true
            - --v=4
